ALTER TABLE option_chain1
ADD COLUMN id BIGSERIAL PRIMARY KEY,
ADD COLUMN strike_price bigint,
ADD COLUMN expiry_date date,
ADD COLUMN CE_strike_price bigint,
ADD COLUMN CE_expiry_date varchar[125] ,
ADD COLUMN CE_underlying varchar[125] ,
ADD COLUMN CE_identifier varchar[125] ,
ADD COLUMN CE_open_interest float8 ,
ADD COLUMN CE_changein_open_interest bigint ,
ADD COLUMN CE_pchangein_open_interest float8 ,
ADD COLUMN CE_total_traded_volume bigint ,
ADD COLUMN CE_implied_volatility float8 ,
ADD COLUMN CE_last_price float8 ,
ADD COLUMN CE_change float8 ,
ADD COLUMN CE_pchange float8 ,
ADD COLUMN CE_total_buy_quantity bigint ,
ADD COLUMN CE_total_sell_quantity bigint ,
ADD COLUMN CE_bid_qty bigint ,
ADD COLUMN CE_bidprice float8 ,
ADD COLUMN CE_ask_qty bigint ,
ADD COLUMN CE_ask_price float8 ,
ADD COLUMN CE_underlying_value float8 ,

ADD COLUMN PE_strike_price bigint ,
ADD COLUMN PE_expiry_date varchar[125] ,
ADD COLUMN PE_underlying varchar[125] ,
ADD COLUMN PE_identifier varchar[125] ,
ADD COLUMN PE_open_interest float8 ,
ADD COLUMN PE_changein_open_interest bigint ,
ADD COLUMN PE_pchangein_open_interest float8 ,
ADD COLUMN PE_total_traded_volume bigint ,
ADD COLUMN PE_implied_volatility float8 ,
ADD COLUMN PE_last_price float8 ,
ADD COLUMN PE_change float8 ,
ADD COLUMN PE_pchange float8 ,
ADD COLUMN PE_total_buy_quantity bigint ,
ADD COLUMN PE_total_sell_quantity bigint ,
ADD COLUMN PE_bid_qty bigint ,
ADD COLUMN PE_bidprice float8 ,
ADD COLUMN PE_ask_qty bigint ,
ADD COLUMN PE_ask_price float8 ,
ADD COLUMN PE_underlying_value float8


